/**
 * Centralized Route Map for all mvfds roles.
 * Single source of truth for navigation links, layout paths, and redirect guards.
 */

export const ROUTES = {
  PUBLIC: {
    HOME: "/",
    ABOUT: "/about",
    CAREERS: "/careers",
    PRIVACY: "/privacy",
    TERMS: "/terms",
    REFUND: "/refund",
    CONTACT: "/contact",
    FAQ: "/faq",
    HELP: "/help",
    RESTAURANTS: "/restaurants",
    RESTAURANT_DETAIL: (id: string) => `/restaurants/${id}`,
    CATEGORIES: "/categories",
    MENU_ITEM: (restaurantId: string, itemId: string) =>
      `/menu/${restaurantId}/${itemId}`,
    UNSUBSCRIBE: "/unsubscribe",
  },
  AUTH: {
    LOGIN: "/login",
    REGISTER: "/register",
    VENDOR_REGISTER: "/vendor/register",
    RIDER_REGISTER: "/rider/register",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    VERIFY_EMAIL: "/verify-email",
    GOOGLE_CALLBACK: "/auth/google/callback",
    ONBOARDING: "/onboarding",
    VENDOR_ONBOARDING: "/vendor/onboarding",
    RIDER_ONBOARDING: "/rider/onboarding",
  },
  CUSTOMER: {
    PROFILE: "/profile",
    FAVORITES: "/favorites",
    CART: "/cart",
    CHECKOUT: "/checkout",
    ORDERS: "/orders",
    ORDER_DETAIL: (id: string) => `/orders/${id}`,
    RESERVATIONS: "/reservations",
    RESERVATION_DETAIL: (id: string) => `/reservations/${id}`,
    NOTIFICATIONS: "/notifications",
    SUPPORT: "/support",
    CREATE_TICKET: "/support/new",
    TICKET_DETAIL: (id: string) => `/support/${id}`,
  },
  VENDOR: {
    DASHBOARD: "/vendor",
    RESTAURANTS: "/vendor/restaurants",
    NEW_RESTAURANT: "/vendor/restaurants/new",
    EDIT_RESTAURANT: (id: string) => `/vendor/restaurants/${id}/edit`,
    MENU: "/vendor/menu",
    NEW_MENU_ITEM: "/vendor/menu/items/new",
    EDIT_MENU_ITEM: (id: string) => `/vendor/menu/items/${id}/edit`,
    ORDERS: "/vendor/orders",
    ORDER_DETAIL: (id: string) => `/vendor/orders/${id}`,
    RESERVATIONS: "/vendor/reservations",
    RESERVATION_SETTINGS: "/vendor/reservations/settings",
    REVIEWS: "/vendor/reviews",
    PROMOTIONS: "/vendor/promotions",
    ANALYTICS: "/vendor/analytics",
    EARNINGS: "/vendor/earnings",
    CUSTOMERS: "/vendor/customers",
    SETTINGS: "/vendor/settings",
    SUPPORT: "/vendor/support",
    CREATE_TICKET: "/vendor/support/new",
    TICKET_DETAIL: (id: string) => `/vendor/support/${id}`,
  },
  RIDER: {
    DASHBOARD: "/rider",
    AVAILABLE: "/rider/available",
    ACTIVE: "/rider/active",
    EARNINGS: "/rider/earnings",
    HISTORY: "/rider/history",
    PROFILE: "/rider/profile",
    SUPPORT: "/rider/support",
  },
  ADMIN: {
    DASHBOARD: "/admin",
    ANALYTICS: "/admin/analytics",
    USERS: "/admin/users",
    APPROVAL_QUEUE: "/admin/approval-queue",
    RESTAURANTS: "/admin/restaurants",
    MENU_ITEMS: "/admin/menu-items",
    DRIVERS: "/admin/drivers",
    DRIVER_DETAIL: (id: string) => `/admin/drivers/${id}`,
    ORDERS: "/admin/orders",
    FLEET_MAP: "/admin/fleet-map",
    RESERVATIONS: "/admin/reservations",
    TAXONOMY: "/admin/taxonomy",
    BANNERS: "/admin/banners",
    SUPPORT: "/admin/support",
    SUPPORT_DETAIL: (id: string) => `/admin/support/${id}`,
    AUDIT_LOGS: "/admin/audit-logs",
    SETTINGS: "/admin/settings",
  },
} as const;

export default ROUTES;
