/**
 * Food Image Manifest — Authoritative Registry of Canonical Dishes
 *
 * Each dish defines:
 * - slug: kebab-case unique identifier matching image file <slug>.webp
 * - displayName: Human readable English name
 * - image: Resolved asset path or Vite-bundled asset URL
 * - aliases: Exact names (English, Bangla, transliterations) that map directly
 * - keywords: Array of required token groups. A group matches if all tokens in that group are present.
 * - excludeKeywords: Tokens that immediately disqualify this dish (prevent false positives)
 * - priority: Higher priority wins when multiple dishes match
 */

// Eager glob import for Vite production bundling:
const globbedImages: Record<string, string> = {};
if (typeof import.meta !== 'undefined' && typeof (import.meta as any).glob === 'function') {
  const eagerMap = (import.meta as any).glob('./*.webp', { eager: true, import: 'default' });
  for (const [key, val] of Object.entries(eagerMap)) {
    const slug = key.replace('./', '').replace('.webp', '');
    globbedImages[slug] = val as string;
  }
}

export const GENERIC_FOOD_PLACEHOLDER: string =
  globbedImages['generic-food-placeholder'] || '/src/assets/foods/generic-food-placeholder.webp';

export function getDishAsset(slug: string): string {
  return globbedImages[slug] || `/src/assets/foods/${slug}.webp`;
}

export interface CanonicalDish {
  slug: string;
  displayName: string;
  image: string;
  priority: number;
  aliases: string[];
  keywords: string[][];
  excludeKeywords: string[];
}

export const CANONICAL_FOOD_MANIFEST: CanonicalDish[] = [
  // ── High Specificity Fried / Fast Food ──
  {
    slug: 'chicken-wings',
    displayName: 'Chicken Wings',
    image: getDishAsset('chicken-wings'),
    priority: 95,
    aliases: ['chicken wings', 'hot wings', 'buffalo wings', 'চিকেন উইংস', 'উইংস'],
    keywords: [['wings'], ['wing']],
    excludeKeywords: ['curry', 'rice', 'biryani', 'pizza'],
  },
  {
    slug: 'chicken-nuggets',
    displayName: 'Chicken Nuggets',
    image: getDishAsset('chicken-nuggets'),
    priority: 95,
    aliases: ['chicken nuggets', 'nuggets', 'চিকেন নাগেটস'],
    keywords: [['nugget'], ['nuggets']],
    excludeKeywords: ['curry', 'rice', 'biryani', 'sandwich', 'burger'],
  },
  {
    slug: 'chicken-tenders',
    displayName: 'Chicken Tenders',
    image: getDishAsset('chicken-tenders'),
    priority: 95,
    aliases: ['chicken tenders', 'tenders', 'chicken strips'],
    keywords: [['tender'], ['tenders']],
    excludeKeywords: ['curry', 'rice', 'biryani', 'sandwich', 'burger'],
  },
  {
    slug: 'club-sandwich',
    displayName: 'Club Sandwich',
    image: getDishAsset('club-sandwich'),
    priority: 95,
    aliases: ['club sandwich', 'ক্লাব স্যান্ডউইচ'],
    keywords: [['club', 'sandwich']],
    excludeKeywords: ['burger', 'pizza', 'roll'],
  },
  {
    slug: 'chicken-sandwich',
    displayName: 'Grilled Chicken Sandwich',
    image: getDishAsset('chicken-sandwich'),
    priority: 90,
    aliases: ['grilled chicken sandwich', 'chicken sandwich', 'চিকেন স্যান্ডউইচ'],
    keywords: [['chicken', 'sandwich']],
    excludeKeywords: ['club', 'burger', 'roll', 'curry'],
  },
  {
    slug: 'hot-dog',
    displayName: 'Hot Dog',
    image: getDishAsset('hot-dog'),
    priority: 95,
    aliases: ['hot dog', 'hotdog', 'হটডগ'],
    keywords: [['hot', 'dog'], ['hotdog']],
    excludeKeywords: ['burger', 'sandwich', 'pizza'],
  },
  {
    slug: 'french-fries',
    displayName: 'French Fries',
    image: getDishAsset('french-fries'),
    priority: 88,
    aliases: ['french fries', 'fries', 'loaded fries', 'cheesy fries', 'ফ্রেঞ্চ ফ্রাই'],
    keywords: [['fries'], ['french', 'fry']],
    excludeKeywords: ['chicken', 'fish', 'rice', 'begun', 'eggplant', 'burger'],
  },
  {
    slug: 'onion-rings',
    displayName: 'Onion Rings',
    image: getDishAsset('onion-rings'),
    priority: 95,
    aliases: ['onion rings', 'অনিয়ন রিংস'],
    keywords: [['onion', 'ring'], ['onion', 'rings']],
    excludeKeywords: ['curry', 'burger', 'pizza'],
  },
  {
    slug: 'garlic-bread',
    displayName: 'Garlic Bread',
    image: getDishAsset('garlic-bread'),
    priority: 92,
    aliases: ['garlic bread', 'garlic breadsticks', 'গার্লিক ব্রেড'],
    keywords: [['garlic', 'bread'], ['garlic', 'breadsticks']],
    excludeKeywords: ['naan', 'roti', 'paratha', 'curry'],
  },
  {
    slug: 'coleslaw',
    displayName: 'Coleslaw',
    image: getDishAsset('coleslaw'),
    priority: 95,
    aliases: ['coleslaw', 'cole slaw'],
    keywords: [['coleslaw'], ['cole', 'slaw']],
    excludeKeywords: ['burger', 'sandwich'],
  },

  // ── Traditional Bengali & Rice Dishes ──
  {
    slug: 'kachchi-biryani',
    displayName: 'Kachchi Biryani',
    image: getDishAsset('kachchi-biryani'),
    priority: 98,
    aliases: ['kachchi biryani', 'kacchi biryani', 'mutton kacchi', 'কাচ্চি বিরিয়ানি', 'কাচ্চি'],
    keywords: [['kacchi'], ['kachchi']],
    excludeKeywords: ['chicken', 'tehari', 'polao'],
  },
  {
    slug: 'chicken-biryani',
    displayName: 'Chicken Biryani',
    image: getDishAsset('chicken-biryani'),
    priority: 94,
    aliases: ['chicken biryani', 'চিকেন বিরিয়ানি'],
    keywords: [['chicken', 'biryani']],
    excludeKeywords: ['kacchi', 'kachchi', 'tehari', 'roll', 'curry', 'pizza'],
  },
  {
    slug: 'beef-tehari',
    displayName: 'Beef Tehari',
    image: getDishAsset('beef-tehari'),
    priority: 96,
    aliases: ['beef tehari', 'tehari', 'beef teheri', 'তেহারি', 'বিফ তেহারি'],
    keywords: [['tehari'], ['teheri'], ['tahari']],
    excludeKeywords: ['biryani', 'polao', 'curry', 'khichuri'],
  },
  {
    slug: 'biryani',
    displayName: 'Biryani (Traditional)',
    image: getDishAsset('biryani'),
    priority: 75,
    aliases: ['biryani', 'mutton biryani', 'beef biryani', 'বিরিয়ানি'],
    keywords: [['biryani']],
    excludeKeywords: ['chicken', 'kacchi', 'kachchi', 'tehari', 'pizza', 'roll'],
  },
  {
    slug: 'khichuri',
    displayName: 'Khichuri',
    image: getDishAsset('khichuri'),
    priority: 92,
    aliases: ['khichuri', 'bhuna khichuri', 'khichri', 'খিচুড়ি'],
    keywords: [['khichuri'], ['khichri']],
    excludeKeywords: ['biryani', 'tehari', 'polao'],
  },
  {
    slug: 'polao',
    displayName: 'Polao (Pulao)',
    image: getDishAsset('polao'),
    priority: 90,
    aliases: ['polao', 'pulao', 'pilau', 'পোলাও'],
    keywords: [['polao'], ['pulao']],
    excludeKeywords: ['biryani', 'tehari', 'khichuri', 'fried'],
  },
  {
    slug: 'chicken-roast',
    displayName: 'Chicken Roast (Bengali Style)',
    image: getDishAsset('chicken-roast'),
    priority: 94,
    aliases: ['chicken roast', 'bengali chicken roast', 'চিকেন রোস্ট'],
    keywords: [['chicken', 'roast']],
    excludeKeywords: ['beef', 'mutton', 'biryani', 'sandwich', 'burger'],
  },
  {
    slug: 'beef-bhuna',
    displayName: 'Beef Bhuna',
    image: getDishAsset('beef-bhuna'),
    priority: 92,
    aliases: ['beef bhuna', 'গরুর মাংস ভুনা', 'বিফ ভুনা'],
    keywords: [['beef', 'bhuna']],
    excludeKeywords: ['mutton', 'chicken', 'khichuri', 'tehari', 'burger'],
  },
  {
    slug: 'mutton-bhuna',
    displayName: 'Mutton Bhuna',
    image: getDishAsset('mutton-bhuna'),
    priority: 92,
    aliases: ['mutton bhuna', 'খাসির মাংস ভুনা', 'মাটন ভুনা'],
    keywords: [['mutton', 'bhuna'], ['goat', 'bhuna'], ['lamb', 'bhuna']],
    excludeKeywords: ['beef', 'chicken', 'khichuri', 'biryani'],
  },
  {
    slug: 'beef-curry',
    displayName: 'Beef Curry',
    image: getDishAsset('beef-curry'),
    priority: 88,
    aliases: ['beef curry', 'beef curry rice', 'বিফ কারি', 'গরুর মাংসের তরকারি'],
    keywords: [['beef', 'curry'], ['beef', 'torkari']],
    excludeKeywords: ['bhuna', 'tehari', 'burger', 'sandwich'],
  },
  {
    slug: 'fish-curry',
    displayName: 'Fish Curry (Macher Jhol)',
    image: getDishAsset('fish-curry'),
    priority: 92,
    aliases: ['fish curry', 'macher jhol', 'মাছের ঝোল', 'মাছ ভুনা'],
    keywords: [['fish', 'curry'], ['macher', 'jhol'], ['fish', 'jhol']],
    excludeKeywords: ['fry', 'finger', 'cake', 'soup'],
  },
  {
    slug: 'chicken-curry',
    displayName: 'Chicken Curry',
    image: getDishAsset('chicken-curry'),
    priority: 88,
    aliases: ['chicken curry', 'murgir torkari', 'চিকেন কারি', 'মুরগির মাংসের ঝোল'],
    keywords: [['chicken', 'curry'], ['murgir', 'jhol']],
    excludeKeywords: ['roast', 'fry', 'burger', 'sandwich', 'butter', 'tikka', 'biryani'],
  },
  {
    slug: 'mutton-curry',
    displayName: 'Mutton Curry',
    image: getDishAsset('mutton-curry'),
    priority: 88,
    aliases: ['mutton curry', 'খাসির মাংসের ঝোল', 'মাটন কারি'],
    keywords: [['mutton', 'curry']],
    excludeKeywords: ['bhuna', 'biryani', 'kacchi'],
  },
  {
    slug: 'daal',
    displayName: 'Daal (Lentil Soup / Makhani)',
    image: getDishAsset('daal'),
    priority: 85,
    aliases: ['daal', 'dal', 'dal makhani', 'lentil soup', 'ডাল'],
    keywords: [['daal'], ['dal'], ['makhani']],
    excludeKeywords: ['khichuri', 'puri', 'paratha'],
  },
  {
    slug: 'aloo-bhorta',
    displayName: 'Aloo Bhorta',
    image: getDishAsset('aloo-bhorta'),
    priority: 96,
    aliases: ['aloo bhorta', 'alu bhorta', 'mashed potato bengali', 'আলু ভর্তা'],
    keywords: [['aloo', 'bhorta'], ['alu', 'bhorta']],
    excludeKeywords: ['begun', 'shutki', 'dim'],
  },
  {
    slug: 'begun-fry',
    displayName: 'Begun Fry (Eggplant Fry)',
    image: getDishAsset('begun-fry'),
    priority: 96,
    aliases: ['begun fry', 'begun bhaja', 'fried eggplant', 'বেগুন ভাজা'],
    keywords: [['begun', 'fry'], ['begun', 'bhaja'], ['eggplant', 'fry']],
    excludeKeywords: ['bhorta', 'curry'],
  },
  {
    slug: 'shutki-bhorta',
    displayName: 'Shutki Bhorta',
    image: getDishAsset('shutki-bhorta'),
    priority: 96,
    aliases: ['shutki bhorta', 'dry fish bhorta', 'শুঁটকি ভর্তা'],
    keywords: [['shutki']],
    excludeKeywords: ['curry', 'fry'],
  },

  // ── Street Food & Snacks ──
  {
    slug: 'chotpoti',
    displayName: 'Chotpoti',
    image: getDishAsset('chotpoti'),
    priority: 98,
    aliases: ['chotpoti', 'chatpati', 'চটপটি'],
    keywords: [['chotpoti'], ['chatpati']],
    excludeKeywords: ['fuchka', 'phuchka'],
  },
  {
    slug: 'fuchka',
    displayName: 'Fuchka (Phuchka / Golgappa)',
    image: getDishAsset('fuchka'),
    priority: 98,
    aliases: ['fuchka', 'phuchka', 'puchka', 'golgappa', 'panipuri', 'ফুচকা'],
    keywords: [['fuchka'], ['phuchka'], ['puchka'], ['golgappa'], ['panipuri']],
    excludeKeywords: ['chotpoti'],
  },
  {
    slug: 'jhal-muri',
    displayName: 'Jhal Muri',
    image: getDishAsset('jhal-muri'),
    priority: 98,
    aliases: ['jhal muri', 'jhalmuri', 'ঝাল মুড়ি', 'ঝালমুড়ি'],
    keywords: [['jhal', 'muri'], ['jhalmuri']],
    excludeKeywords: [],
  },
  {
    slug: 'samosa',
    displayName: 'Samosa / Singara',
    image: getDishAsset('samosa'),
    priority: 92,
    aliases: ['samosa', 'shingara', 'singara', 'সিঙ্গারা', 'সমুচা'],
    keywords: [['samosa'], ['shingara'], ['singara'], ['somucha']],
    excludeKeywords: ['chaat'],
  },
  {
    slug: 'pakora',
    displayName: 'Pakora',
    image: getDishAsset('pakora'),
    priority: 92,
    aliases: ['pakora', 'pakoda', 'পাকোড়া'],
    keywords: [['pakora'], ['pakoda']],
    excludeKeywords: [],
  },
  {
    slug: 'spring-rolls',
    displayName: 'Spring Rolls',
    image: getDishAsset('spring-rolls'),
    priority: 94,
    aliases: ['spring rolls', 'spring roll', 'স্প্রিং রোল'],
    keywords: [['spring', 'roll'], ['spring', 'rolls']],
    excludeKeywords: ['egg roll', 'chicken roll'],
  },

  // ── Pizza Varieties ──
  {
    slug: 'pizza-margherita',
    displayName: 'Margherita Pizza',
    image: getDishAsset('pizza-margherita'),
    priority: 96,
    aliases: ['margherita', 'margherita pizza', 'মার্গারিটা পিজ্জা'],
    keywords: [['margherita']],
    excludeKeywords: ['chicken', 'beef', 'pepperoni'],
  },
  {
    slug: 'pizza-pepperoni',
    displayName: 'Pepperoni Pizza',
    image: getDishAsset('pizza-pepperoni'),
    priority: 96,
    aliases: ['pepperoni', 'pepperoni pizza', 'পেপেরনি পিজ্জা'],
    keywords: [['pepperoni']],
    excludeKeywords: ['chicken', 'veggie'],
  },
  {
    slug: 'pizza-chicken',
    displayName: 'Chicken Tikka / BBQ Pizza',
    image: getDishAsset('pizza-chicken'),
    priority: 94,
    aliases: ['chicken tikka pizza', 'bbq chicken pizza', 'চিকেন পিজ্জা'],
    keywords: [['bbq', 'chicken'], ['tikka', 'pizza'], ['chicken', 'pizza']],
    excludeKeywords: ['burger', 'sandwich', 'roll'],
  },
  {
    slug: 'pizza-veggie',
    displayName: 'Veggie Supreme Pizza',
    image: getDishAsset('pizza-veggie'),
    priority: 92,
    aliases: ['veggie supreme', 'vegetarian pizza', 'ভেজি পিজ্জা'],
    keywords: [['veggie', 'supreme'], ['vegetarian', 'pizza'], ['veggie', 'pizza']],
    excludeKeywords: ['chicken', 'beef', 'meat'],
  },
  {
    slug: 'pizza-meat',
    displayName: 'Meat Lovers Pizza',
    image: getDishAsset('pizza-meat'),
    priority: 92,
    aliases: ['meat lovers', 'meat lovers pizza'],
    keywords: [['meat', 'lover'], ['meat', 'lovers']],
    excludeKeywords: ['veggie', 'margherita'],
  },

  // ── Burgers ──
  {
    slug: 'beef-burger',
    displayName: 'Classic Beef Burger',
    image: getDishAsset('beef-burger'),
    priority: 88,
    aliases: ['classic beef burger', 'double patty burger', 'beef burger', 'বিফ বার্গার'],
    keywords: [['beef', 'burger'], ['double', 'patty']],
    excludeKeywords: ['cheese', 'chicken', 'fish'],
  },
  {
    slug: 'cheeseburger',
    displayName: 'Cheeseburger',
    image: getDishAsset('cheeseburger'),
    priority: 92,
    aliases: ['cheeseburger', 'cheese burger', 'চিজি বার্গার'],
    keywords: [['cheese', 'burger'], ['cheeseburger']],
    excludeKeywords: ['pizza', 'fries'],
  },
  {
    slug: 'chicken-burger',
    displayName: 'Chicken Burger',
    image: getDishAsset('chicken-burger'),
    priority: 88,
    aliases: ['chicken burger', 'spicy jalapeño burger', 'চিকেন বার্গার'],
    keywords: [['chicken', 'burger'], ['jalapeno', 'burger'], ['jalapeño', 'burger']],
    excludeKeywords: ['cheese', 'beef', 'sandwich'],
  },

  // ── Chicken Specialties & Grills ──
  {
    slug: 'fried-chicken',
    displayName: 'Crispy Fried Chicken',
    image: getDishAsset('fried-chicken'),
    priority: 88,
    aliases: ['fried chicken', 'chicken fry', 'chicken 65', 'chicken lollipop', 'crispy chicken', 'ফ্রাইড চিকেন', 'চিকেন ফ্রাই'],
    keywords: [['fried', 'chicken'], ['chicken', 'fry'], ['chicken', '65'], ['lollipop']],
    excludeKeywords: ['burger', 'sandwich', 'curry', 'rice', 'chowmein', 'roll'],
  },
  {
    slug: 'grilled-chicken',
    displayName: 'Grilled Chicken',
    image: getDishAsset('grilled-chicken'),
    priority: 86,
    aliases: ['grilled chicken', 'গ্রিল্ড চিকেন'],
    keywords: [['grilled', 'chicken']],
    excludeKeywords: ['sandwich', 'burger', 'salad', 'bowl', 'curry'],
  },
  {
    slug: 'tandoori-chicken',
    displayName: 'Tandoori Chicken',
    image: getDishAsset('tandoori-chicken'),
    priority: 92,
    aliases: ['tandoori chicken', 'তন্দুরি চিকেন'],
    keywords: [['tandoori', 'chicken'], ['tandoori']],
    excludeKeywords: ['roti', 'naan', 'pizza'],
  },
  {
    slug: 'butter-chicken',
    displayName: 'Butter Chicken / Tikka Masala',
    image: getDishAsset('butter-chicken'),
    priority: 88,
    aliases: ['butter chicken', 'chicken tikka masala', 'chicken vindaloo', 'বাটার চিকেন'],
    keywords: [['butter', 'chicken'], ['tikka', 'masala'], ['vindaloo']],
    excludeKeywords: ['pizza', 'roll', 'burger'],
  },
  {
    slug: 'seekh-kebab',
    displayName: 'Seekh Kebab',
    image: getDishAsset('seekh-kebab'),
    priority: 92,
    aliases: ['seekh kebab', 'shami kebab', 'boti kebab', 'শিক কাবাব', 'কাবাব'],
    keywords: [['seekh'], ['kebab'], ['kabab']],
    excludeKeywords: ['shawarma', 'roll', 'pizza'],
  },

  // ── Asian, Momos, Noodles, Rice ──
  {
    slug: 'momos-steamed',
    displayName: 'Steamed Momos',
    image: getDishAsset('momos-steamed'),
    priority: 94,
    aliases: ['steamed momos', 'jhol momos', 'c momos', 'মোমো'],
    keywords: [['momo'], ['momos']],
    excludeKeywords: ['fried', 'fry'],
  },
  {
    slug: 'momos-fried',
    displayName: 'Fried Momos',
    image: getDishAsset('momos-fried'),
    priority: 96,
    aliases: ['fried momos', 'kothey momo', 'ফ্রাইড মোমো'],
    keywords: [['fried', 'momo'], ['fried', 'momos']],
    excludeKeywords: ['steamed'],
  },
  {
    slug: 'fried-rice',
    displayName: 'Fried Rice',
    image: getDishAsset('fried-rice'),
    priority: 88,
    aliases: ['fried rice', 'chicken rice bowl', 'chicken rice', 'ফ্রাইড রাইস'],
    keywords: [['fried', 'rice'], ['rice', 'bowl']],
    excludeKeywords: ['biryani', 'tehari', 'khichuri', 'polao'],
  },
  {
    slug: 'plain-rice',
    displayName: 'Plain / Jeera Rice',
    image: getDishAsset('plain-rice'),
    priority: 70,
    aliases: ['plain rice', 'jeera rice', 'steamed rice', 'ভাত'],
    keywords: [['plain', 'rice'], ['jeera', 'rice']],
    excludeKeywords: ['fried', 'biryani', 'khichuri', 'polao', 'curry'],
  },
  {
    slug: 'chowmein',
    displayName: 'Chowmein / Noodles',
    image: getDishAsset('chowmein'),
    priority: 90,
    aliases: ['chicken chowmein', 'hakka noodles', 'egg noodles', 'চাউমিন', 'নুডুলস'],
    keywords: [['chowmein'], ['noodles'], ['chow', 'mein']],
    excludeKeywords: ['soup'],
  },
  {
    slug: 'chinese-chicken',
    displayName: 'Chilli Chicken / Manchurian',
    image: getDishAsset('chinese-chicken'),
    priority: 90,
    aliases: ['chilli chicken', 'chicken manchurian', 'sweet & sour chicken', 'sweet and sour chicken'],
    keywords: [['chilli', 'chicken'], ['manchurian'], ['sweet', 'sour', 'chicken']],
    excludeKeywords: ['curry', 'biryani', 'pizza'],
  },
  {
    slug: 'naan',
    displayName: 'Naan Bread',
    image: getDishAsset('naan'),
    priority: 90,
    aliases: ['naan', 'garlic naan', 'butter naan', 'নান'],
    keywords: [['naan']],
    excludeKeywords: ['curry', 'chicken'],
  },

  // ── Desserts & Bakery ──
  {
    slug: 'brownie',
    displayName: 'Chocolate Brownie',
    image: getDishAsset('brownie'),
    priority: 95,
    aliases: ['chocolate brownie', 'brownie', 'ব্রাউনি'],
    keywords: [['brownie']],
    excludeKeywords: [],
  },
  {
    slug: 'cheesecake',
    displayName: 'Cheesecake',
    image: getDishAsset('cheesecake'),
    priority: 95,
    aliases: ['cheesecake', 'cheesecake slice', 'চিজকেক'],
    keywords: [['cheesecake']],
    excludeKeywords: [],
  },
  {
    slug: 'waffle',
    displayName: 'Belgian Waffle',
    image: getDishAsset('waffle'),
    priority: 95,
    aliases: ['waffle', 'belgian waffle', 'ওয়াফেল'],
    keywords: [['waffle']],
    excludeKeywords: [],
  },
  {
    slug: 'pancakes',
    displayName: 'Pancakes Stack',
    image: getDishAsset('pancakes'),
    priority: 95,
    aliases: ['pancake stack', 'pancakes', 'pancake', 'প্যানকেক'],
    keywords: [['pancake'], ['pancakes']],
    excludeKeywords: [],
  },
  {
    slug: 'tiramisu',
    displayName: 'Tiramisu',
    image: getDishAsset('tiramisu'),
    priority: 95,
    aliases: ['tiramisu', 'টিরামিসু'],
    keywords: [['tiramisu']],
    excludeKeywords: [],
  },
  {
    slug: 'lava-cake',
    displayName: 'Molten Lava Cake',
    image: getDishAsset('lava-cake'),
    priority: 95,
    aliases: ['lava cake', 'molten lava cake', 'চকলেট লাভা কেক'],
    keywords: [['lava', 'cake']],
    excludeKeywords: [],
  },
  {
    slug: 'ice-cream-sundae',
    displayName: 'Ice Cream Sundae',
    image: getDishAsset('ice-cream-sundae'),
    priority: 92,
    aliases: ['ice cream sundae', 'sundae', 'আইসক্রিম সানডে'],
    keywords: [['ice', 'cream'], ['sundae']],
    excludeKeywords: ['shake', 'milkshake', 'smoothie'],
  },
  {
    slug: 'cake-slice',
    displayName: 'Cake Slice (Chocolate / Red Velvet)',
    image: getDishAsset('cake-slice'),
    priority: 80,
    aliases: ['chocolate cake', 'red velvet', 'black forest', 'cake slice', 'কেক'],
    keywords: [['cake'], ['red', 'velvet'], ['black', 'forest']],
    excludeKeywords: ['lava', 'cheese', 'pancake'],
  },
];
